apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: tanzu-java-web-app
  annotations: {}
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app
spec:
  type: openapi
  description: A set of API endpoints to manage the resources within the petclinic app.(running on TAP, main)
  system: pet-clinics
  owner: team-petclinic
  location:
    path: /v3/api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: tanzu-java-web-app

